name: Security
main: Security\Security
version: 0.1-beta
author: JacobYun
api: 1.11.0

commands:
 wc:
  description: 플레이어에게 경고횟수를 알려줍니다.
  usage: /wc
 w:
  permission: security.warning.give
  description: 플레이어에게 경고를 부여합니다.
  usage: /w [플레이어] <횟수>

permissions:
 security.warning.give:
  default: op